hw_project/app_auth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = "app_auth"

# urlpatterns = [
#     path('signup/', views.RegisterView.as_view(), name='signup'),
#     path('login/',
#          LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True),
#          name='login'),
#     path('logout/', LogoutView.as_view(template_name='app_auth/logout.html'), name='logout')
# ]


urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    # path('signin/', LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm), name='signin'),
    path("logout/", LogoutView.as_view(template_name='app_auth/logout.html'), name="logout")
]

hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from quotes.views import HomeView




# urlpatterns = ([
#     # path("admin/", admin.site.urls),
#     # path("", include("quotes.urls")),
#     # path("auth/", include('app_auth.urls')),
#     # path("admin/", admin.site.urls),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include('app_auth.urls')),
    path("quotes/", include('quotes.urls')),
    path('', HomeView.as_view(), name='home')
    # path("", include('quotes.urls')),
    # path("", HomeView.as_view(), name='home')
]
# urlpatterns = [
#     path("admin/", admin.site.urls),
#     path("", include("quotes.urls")),
#     # path("users/", include("users.urls"))
# ]

hw_project/quotes/urls.py
from django.urls import path
from .views import AddTagView, AddAuthorView, AddQuoteView, AuthDetailView,QuotesToTag

app_name = "quotes"

urlpatterns = [
    path("add_tag/", AddTagView.as_view(), name='add_tag'),
    path('add_author/', AddAuthorView.as_view(), name='add_author'),
    path('add_quote/', AddQuoteView.as_view(), name='add_quote'),
    path("author/<pk>/", AuthDetailView.as_view(), name="author_detail"),
    path("tag/<slug:slug>/", QuotesToTag.as_view(), name="home"),

]

hw_project/quotes/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.db.models import F


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    # popularity = models.IntegerField(default=0)
    # slug = models.SlugField(max_length=225,unique=True,verbose_name="URL")

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reversed('Tag', kwargs={'tags_slug':self.slug})

    # def increase_popularity(self):
    #     Tag.objects.filter(id=self.id).update(popularity=F("popularity") + 1)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_id = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote[:50]

    # def all_tags(self):
    #     return Quote.objects.get(quote=self.quote).tags.all()

# Create your models here.

hw_project/quotes/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django import forms
from django.contrib.auth.models import User
from django.db import models
from .models import Author, Quote, Tag


class YourRegisterForm(UserCreationForm):
    # Добавьте любые дополнительные поля или настройки, если необходимо
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def clean_email(self):
        # Ваша логика проверки электронной почты здесь
        pass


def register(request):
    if request.method == "POST":
        form = YourRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("your-redirect-url")
    else:
        form = YourRegisterForm()
    return render(request, "registration/register.html", {"form": form})


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']
        widgets = {
            'tag': forms.CheckboxSelectMultiple()
        }

hw_project/quotes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View, generic
from django.http import HttpResponse
from django.views.generic import ListView, CreateView
from django.core.paginator import Paginator
from .forms import TagForm, AuthorForm, QuoteForm
from .models import Quote, Author, Tag

from .utils import get_mongodb


class AuthDetailView(generic.DetailView):
    model = Author


"""Функция main использовалась для загрузки основной страницы из MongoDB"""
def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})
    # return render(request, 'quotes/index.html, context={}')


class HomeView(ListView):
    model = Quote
    template_name = 'home.html'
    context_object_name = 'quotes'
    paginate_by = 7


class QuotesToTag(ListView):
    model = Quote
    template_name = 'home.html'
    context_object_name = 'quotes'
    paginate_by = 7

    def get_queryset(self):
        return Quote.objects.filter(tags__id=self.kwargs['slug'])



class AddTagView(LoginRequiredMixin, CreateView):
    login_url = "/users/login/"
    model = Tag
    template_name = "quotes/add_tag.html"
    success_url = reverse_lazy('home')
    form_class = TagForm


class AddAuthorView(LoginRequiredMixin, CreateView):
    login_url = "/users/login/"
    model = Author
    template_name = "quotes/add_author.html"
    success_url = reverse_lazy('home')
    form_class = AuthorForm


class AddQuoteView(LoginRequiredMixin, CreateView):
    login_url = "/users/login/"
    model = Author
    template_name = "quotes/add_quote.html"
    success_url = reverse_lazy('home')
    form_class = QuoteForm

hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
  <h2>Add Author</h2>
  <form method="post" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Author</button>
  </form>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
  <h2>Add Quote</h2>
  <form method="post" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Quote</button>
  </form>
{% endblock %}

hw_project/quotes/templates/quotes/add_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
  <h2>Add Author</h2>
  <form method="post" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Author</button>
  </form>
{% endblock %}

hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h2>{{ author.fullname }}</h2>
<p> Born date - {{ author.born_date }}</p>
<p> Born location - {{ author.born_location }}</p>
<h2> More details:</h2>
<p>{{ author.description }}</p>
<!-- Другие поля автора, которые вы хотите отобразить -->
{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework_10</title>
</head>
<body>
    <div class="container">
            <div class="row header-box pt-3 mb-3">
                <div class="col-md-8">
                    <h1>
                        <a href='http://127.0.0.1:8000/' style="text-decoration: none">Quotes to Scrape</a>
                    </h1>
                </div>
                <div class="col-md-4">
                    <p>
                        {% if user.is_authenticated %}
                            <form action="{% url 'app_auth:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-light" type="submit">Logout</button>
                            </form>

                            <a href="{% url 'quotes:add_author' %}" class="btn btn-light">Add Author</a>
                            <a href="{% url 'quotes:add_quote' %}" class="btn btn-light">Add Quote</a>
                            <a href="{% url 'quotes:add_tag' %}" class="btn btn-light">Add Tag</a>
                        {% else %}
                            <a href="{% url 'app_auth:signin' %}" class="btn btn-light">Login</a>
                            <a href="{% url 'app_auth:signup' %}" class="btn btn-light">SingUp</a>

                        {% endif %}
                    </p>
                </div>
            </div>


 {% block content%} {% endblock %}
        </div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
   <div class="row">
        <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
               {{quote.quote}}
            </span>

            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}/1/">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"

                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                       Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>

        </nav>
        </div>

    </div>

{% endblock %}

hw_project/quotes/templates/quotes/quotes.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
   <div class="row">
        <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
               {{quote.quote}}
            </span>

            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="/author">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}/1/">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"

                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                       Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>

        </nav>
        </div>

    </div>

{% endblock %}